export interface Country {
    name: string;
    code: string;
    dial: string;
    flag: string;
}

export const COUNTRIES: Country[] = [
    { name: 'Brasil', code: 'BR', dial: '+55', flag: '🇧🇷' },
    { name: 'Estados Unidos', code: 'US', dial: '+1', flag: '🇺🇸' },
    { name: 'Portugal', code: 'PT', dial: '+351', flag: '🇵🇹' },
    { name: 'Argentina', code: 'AR', dial: '+54', flag: '🇦🇷' },
    { name: 'Uruguai', code: 'UY', dial: '+598', flag: '🇺🇾' },
    { name: 'Paraguai', code: 'PY', dial: '+595', flag: '🇵🇾' },
    { name: 'Chile', code: 'CL', dial: '+56', flag: '🇨🇱' },
    { name: 'Colômbia', code: 'CO', dial: '+57', flag: '🇨🇴' },
    { name: 'México', code: 'MX', dial: '+52', flag: '🇲🇽' },
    { name: 'Peru', code: 'PE', dial: '+51', flag: '🇵🇪' },
    { name: 'Venezuela', code: 'VE', dial: '+58', flag: '🇻🇪' },
    { name: 'Bolívia', code: 'BO', dial: '+591', flag: '🇧🇴' },
    { name: 'Equador', code: 'EC', dial: '+593', flag: '🇪🇨' },
    { name: 'Canadá', code: 'CA', dial: '+1', flag: '🇨🇦' },
    { name: 'Reino Unido', code: 'GB', dial: '+44', flag: '🇬🇧' },
    { name: 'França', code: 'FR', dial: '+33', flag: '🇫🇷' },
    { name: 'Alemanha', code: 'DE', dial: '+49', flag: '🇩🇪' },
    { name: 'Espanha', code: 'ES', dial: '+34', flag: '🇪🇸' },
    { name: 'Itália', code: 'IT', dial: '+39', flag: '🇮🇹' },
    { name: 'Holanda', code: 'NL', dial: '+31', flag: '🇳🇱' },
    { name: 'Bélgica', code: 'BE', dial: '+32', flag: '🇧🇪' },
    { name: 'Suíça', code: 'CH', dial: '+41', flag: '🇨🇭' },
    { name: 'Áustria', code: 'AT', dial: '+43', flag: '🇦🇹' },
    { name: 'Suécia', code: 'SE', dial: '+46', flag: '🇸🇪' },
    { name: 'Noruega', code: 'NO', dial: '+47', flag: '🇳🇴' },
    { name: 'Dinamarca', code: 'DK', dial: '+45', flag: '🇩🇰' },
    { name: 'Finlândia', code: 'FI', dial: '+358', flag: '🇫🇮' },
    { name: 'Polônia', code: 'PL', dial: '+48', flag: '🇵🇱' },
    { name: 'Irlanda', code: 'IE', dial: '+353', flag: '🇮🇪' },
    { name: 'Grécia', code: 'GR', dial: '+30', flag: '🇬🇷' },
    { name: 'Turquia', code: 'TR', dial: '+90', flag: '🇹🇷' },
    { name: 'Rússia', code: 'RU', dial: '+7', flag: '🇷🇺' },
    { name: 'China', code: 'CN', dial: '+86', flag: '🇨🇳' },
    { name: 'Japão', code: 'JP', dial: '+81', flag: '🇯🇵' },
    { name: 'Coreia do Sul', code: 'KR', dial: '+82', flag: '🇰🇷' },
    { name: 'Índia', code: 'IN', dial: '+91', flag: '🇮🇳' },
    { name: 'Austrália', code: 'AU', dial: '+61', flag: '🇦🇺' },
    { name: 'Nova Zelândia', code: 'NZ', dial: '+64', flag: '🇳🇿' },
    { name: 'África do Sul', code: 'ZA', dial: '+27', flag: '🇿🇦' },
    { name: 'Egito', code: 'EG', dial: '+20', flag: '🇪🇬' },
    { name: 'Nigéria', code: 'NG', dial: '+234', flag: '🇳🇬' },
    { name: 'Marrocos', code: 'MA', dial: '+212', flag: '🇲🇦' },
    { name: 'Emirados Árabes', code: 'AE', dial: '+971', flag: '🇦🇪' },
    { name: 'Arábia Saudita', code: 'SA', dial: '+966', flag: '🇸🇦' },
    { name: 'Israel', code: 'IL', dial: '+972', flag: '🇮🇱' },
    { name: 'Tailândia', code: 'TH', dial: '+66', flag: '🇹🇭' },
    { name: 'Indonésia', code: 'ID', dial: '+62', flag: '🇮🇩' },
    { name: 'Malásia', code: 'MY', dial: '+60', flag: '🇲🇾' },
    { name: 'Filipinas', code: 'PH', dial: '+63', flag: '🇵🇭' },
    { name: 'Singapura', code: 'SG', dial: '+65', flag: '🇸🇬' },
    { name: 'Taiwan', code: 'TW', dial: '+886', flag: '🇹🇼' },
    { name: 'Hong Kong', code: 'HK', dial: '+852', flag: '🇭🇰' },
    { name: 'Paquistão', code: 'PK', dial: '+92', flag: '🇵🇰' },
    { name: 'Bangladesh', code: 'BD', dial: '+880', flag: '🇧🇩' },
    { name: 'Vietnã', code: 'VN', dial: '+84', flag: '🇻🇳' },
    { name: 'Costa Rica', code: 'CR', dial: '+506', flag: '🇨🇷' },
    { name: 'Panamá', code: 'PA', dial: '+507', flag: '🇵🇦' },
    { name: 'Guatemala', code: 'GT', dial: '+502', flag: '🇬🇹' },
    { name: 'Cuba', code: 'CU', dial: '+53', flag: '🇨🇺' },
    { name: 'República Dominicana', code: 'DO', dial: '+1', flag: '🇩🇴' },
    { name: 'Porto Rico', code: 'PR', dial: '+1', flag: '🇵🇷' },
    { name: 'Jamaica', code: 'JM', dial: '+1', flag: '🇯🇲' },
    { name: 'Angola', code: 'AO', dial: '+244', flag: '🇦🇴' },
    { name: 'Moçambique', code: 'MZ', dial: '+258', flag: '🇲🇿' },
    { name: 'Cabo Verde', code: 'CV', dial: '+238', flag: '🇨🇻' },
    { name: 'Guiné-Bissau', code: 'GW', dial: '+245', flag: '🇬🇼' },
    { name: 'São Tomé e Príncipe', code: 'ST', dial: '+239', flag: '🇸🇹' },
    { name: 'Timor-Leste', code: 'TL', dial: '+670', flag: '🇹🇱' },
    { name: 'Romênia', code: 'RO', dial: '+40', flag: '🇷🇴' },
    { name: 'Ucrânia', code: 'UA', dial: '+380', flag: '🇺🇦' },
    { name: 'Hungria', code: 'HU', dial: '+36', flag: '🇭🇺' },
    { name: 'República Tcheca', code: 'CZ', dial: '+420', flag: '🇨🇿' },
    { name: 'Croácia', code: 'HR', dial: '+385', flag: '🇭🇷' },
    { name: 'Sérvia', code: 'RS', dial: '+381', flag: '🇷🇸' },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Brasil
